package gsb_frai;

import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author cjoncour
 */
public class Fenetre_Modifier extends javax.swing.JFrame {
        AccesBdD connectBdd = new AccesBdD();
        private JFrame parentFrame;
        private UtilisateurDAO utDAO = new UtilisateurDAO(connectBdd.getConnexion());

    /**
     * Creates new form Fenetre_Modifier
     */
    public Fenetre_Modifier(JFrame parent) {
        initComponents();
        this.connectBdd = new AccesBdD();
        this.parentFrame = parent;
        this.utDAO = new UtilisateurDAO(connectBdd.getConnexion());
    }

    private Fenetre_Modifier() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_titre = new javax.swing.JLabel();
        lbl_prenom = new javax.swing.JLabel();
        lbl_nom = new javax.swing.JLabel();
        txt_idModif = new javax.swing.JTextField();
        txt_nom = new javax.swing.JTextField();
        lbl_adr = new javax.swing.JLabel();
        txt_adr = new javax.swing.JTextField();
        txt_ville = new javax.swing.JTextField();
        lbl_ville = new javax.swing.JLabel();
        txt_cpostale = new javax.swing.JTextField();
        lbl_cpostale = new javax.swing.JLabel();
        lbl_statut = new javax.swing.JLabel();
        btn_valider = new javax.swing.JButton();
        jDate_dateEmb = new com.toedter.calendar.JDateChooser();
        lbl_dateEmb1 = new javax.swing.JLabel();
        jComb_Statut = new javax.swing.JComboBox<>();
        lbl_idModif = new javax.swing.JLabel();
        txt_prenom = new javax.swing.JTextField();
        lbl_login = new javax.swing.JLabel();
        txt_login = new javax.swing.JTextField();
        lbl_mdp = new javax.swing.JLabel();
        txt_mdp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(150, 181, 236));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        lbl_titre.setBackground(new java.awt.Color(150, 181, 236));
        lbl_titre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_titre.setForeground(new java.awt.Color(0, 0, 0));
        lbl_titre.setText("Modifier");

        lbl_prenom.setBackground(new java.awt.Color(150, 181, 236));
        lbl_prenom.setForeground(new java.awt.Color(0, 0, 0));
        lbl_prenom.setText("Prénom");

        lbl_nom.setForeground(new java.awt.Color(0, 0, 0));
        lbl_nom.setText("Nom");

        txt_idModif.setBackground(new java.awt.Color(255, 255, 255));

        txt_nom.setBackground(new java.awt.Color(255, 255, 255));
        txt_nom.setForeground(new java.awt.Color(0, 0, 0));

        lbl_adr.setForeground(new java.awt.Color(0, 0, 0));
        lbl_adr.setText("Adresse");

        lbl_ville.setForeground(new java.awt.Color(0, 0, 0));
        lbl_ville.setText("Ville");

        lbl_cpostale.setForeground(new java.awt.Color(0, 0, 0));
        lbl_cpostale.setText("Code Postale");

        lbl_statut.setForeground(new java.awt.Color(0, 0, 0));
        lbl_statut.setText("Statut");

        btn_valider.setBackground(new java.awt.Color(164, 254, 133));
        btn_valider.setForeground(new java.awt.Color(0, 0, 0));
        btn_valider.setText("Valider");
        btn_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_validerActionPerformed(evt);
            }
        });

        lbl_dateEmb1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_dateEmb1.setText("Date d'embauche");

        jComb_Statut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Visiteur", "RH" }));

        lbl_idModif.setForeground(new java.awt.Color(0, 0, 0));
        lbl_idModif.setText("id à modifier");

        txt_prenom.setBackground(new java.awt.Color(255, 255, 255));

        lbl_login.setForeground(new java.awt.Color(0, 0, 0));
        lbl_login.setText("Login");

        txt_login.setBackground(new java.awt.Color(255, 255, 255));

        lbl_mdp.setForeground(new java.awt.Color(0, 0, 0));
        lbl_mdp.setText("Mot de passe");

        txt_mdp.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(lbl_titre))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_mdp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_nom)
                                    .addComponent(lbl_adr)
                                    .addComponent(lbl_ville))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_adr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ville, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_cpostale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_cpostale, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_statut)
                                    .addComponent(btn_valider, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDate_dateEmb, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                    .addComponent(jComb_Statut, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_idModif)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_idModif, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_prenom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_login)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_dateEmb1)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titre)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_prenom)
                            .addComponent(txt_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_nom))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_adr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_adr))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ville, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_ville))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cpostale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_cpostale))
                        .addGap(18, 18, 18)
                        .addComponent(jDate_dateEmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_dateEmb1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_statut)
                    .addComponent(jComb_Statut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_idModif)
                    .addComponent(txt_idModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_login)
                    .addComponent(txt_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_mdp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btn_valider)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_validerActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "Voulez vous sauvegarder la/les modification(s) ?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            // If the user chose 'Yes', show a message indicating that changes are saved
            JOptionPane.showMessageDialog(null, "Modification(s) sauvegardée(s)");
            //Ferme la fenêtre Fenetre_Modification
            this.dispose();
            if(parentFrame != null){
                parentFrame.setVisible(true);
                int statut = 2;
                if(jComb_Statut.getSelectedItem() == "RH"){
                    statut = 1;
                }
                else if(jComb_Statut.getSelectedItem() == "Visiteur"){
                    statut = 2;
                }
                try {
                    utDAO.modifVisiteurs(txt_nom.getText(), txt_prenom.getText(), txt_login.getText(), txt_mdp.getText(), txt_adr.getText(), txt_cpostale.getText(), txt_ville.getText(), jDate_dateEmb.getDate(), statut, txt_idModif.getText());
                } catch (SQLException ex) {
                    Logger.getLogger(Fenetre_Modifier.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else{
                System.out.println("Fenêtre ne fonctionne pas");
            }
        }
        else if (result == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "Modification(s) non sauvegardée(s)");
        }
    }//GEN-LAST:event_btn_validerActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Modifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Modifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Modifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Modifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetre_Modifier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_valider;
    private javax.swing.JComboBox<String> jComb_Statut;
    private com.toedter.calendar.JDateChooser jDate_dateEmb;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_adr;
    private javax.swing.JLabel lbl_cpostale;
    private javax.swing.JLabel lbl_dateEmb1;
    private javax.swing.JLabel lbl_idModif;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lbl_mdp;
    private javax.swing.JLabel lbl_nom;
    private javax.swing.JLabel lbl_prenom;
    private javax.swing.JLabel lbl_statut;
    private javax.swing.JLabel lbl_titre;
    private javax.swing.JLabel lbl_ville;
    private javax.swing.JTextField txt_adr;
    private javax.swing.JTextField txt_cpostale;
    private javax.swing.JTextField txt_idModif;
    private javax.swing.JTextField txt_login;
    private javax.swing.JTextField txt_mdp;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_prenom;
    private javax.swing.JTextField txt_ville;
    // End of variables declaration//GEN-END:variables
}
